version: '3.8'

networks:
  bank-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  kafka-data:

services:
  bank-postgres:
    image: postgres:15-alpine
    container_name: bank_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - bank-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  bank-redis:
    image: redis:7-alpine
    container_name: bank_redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - bank-network
    volumes:
      - redis-data:/data

  bank-kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: bank_kafka
    restart: unless-stopped
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://bank_kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@bank_kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://bank_kafka:29092,CONTROLLER://bank_kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - bank-network
    volumes:
      - kafka-data:/tmp/kraft-combined-logs

  bank-core:
    image: ghcr.io/ilya-ivanov23/idpbankapp23-core-engine:latest
    container_name: bank_core
    restart: unless-stopped
    depends_on:
      - bank-postgres
      - bank-kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bank-postgres:5432/idp_bank_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=bank-kafka:29092
    networks:
      - bank-network
